/*
Copyright 2026 The KrakenD Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package autoconfig

import (
	"context"
	"fmt"
	"strings"

	v1alpha1 "github.com/mycarrier-devops/krakend-operator/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// Labels every generated KrakenDEndpoint carries. LabelAutoConfig holds the
// owning AutoConfig's name.
const (
	LabelAutoConfig    = "gateway.krakend.io/autoconfig"
	LabelAutoGenerated = "gateway.krakend.io/auto-generated"
)

// GenerateInput provides the data needed to generate KrakenDEndpoint CRs.
type GenerateInput struct {
	AutoConfig       *v1alpha1.KrakenDAutoConfig
	Entries          []v1alpha1.EndpointEntry
	OperationIDs     map[string]string
	GatewayRef       v1alpha1.GatewayRef
	ComponentSchemas map[string]runtime.RawExtension
}

// GenerateOutput contains the generated endpoint CRs and metadata.
type GenerateOutput struct {
	Endpoints []*v1alpha1.KrakenDEndpoint
	// Skipped holds the entries dropped as duplicates of an earlier entry
	// (reason DuplicateOperationId), in entry order.
	Skipped           []OperationIssue
	SkippedOperations int
	// Duplicates holds the identifiers that caused deduplication skips.
	// Each entry may be a path:method key, an operationId, or a generated name.
	Duplicates []string
}

// Generator wraps endpoint entries in KrakenDEndpoint CRs with metadata and labels.
type Generator interface {
	Generate(ctx context.Context, input GenerateInput) (*GenerateOutput, error)
}

// NewGenerator returns a Generator implementation.
func NewGenerator() Generator {
	return &endpointGenerator{}
}

type endpointGenerator struct{}

func (g *endpointGenerator) Generate(
	_ context.Context,
	input GenerateInput,
) (*GenerateOutput, error) {
	ac := input.AutoConfig
	seenKeys := map[string]string{}
	seenOperationIDs := map[string]string{}
	seenNames := map[string]string{}
	output := &GenerateOutput{}

	for _, entry := range input.Entries {
		key := entry.Endpoint + ":" + entry.Method
		opID := input.OperationIDs[key]
		name := endpointName(ac.Name, opID, entry.Method, entry.Endpoint)
		op := entry.Method + " " + entry.Endpoint

		if ident, dup := duplicateOf(key, opID, name, seenKeys, seenOperationIDs, seenNames); dup != "" {
			output.SkippedOperations++
			output.Duplicates = append(output.Duplicates, ident)
			output.Skipped = append(output.Skipped, OperationIssue{
				Operation: Operation{Method: entry.Method, Path: entry.Endpoint, OperationID: opID},
				Reason:    v1alpha1.ReasonDuplicateOperationId,
				Message:   dup,
			})
			continue
		}
		seenKeys[key] = op
		if opID != "" {
			seenOperationIDs[opID] = op
		}
		seenNames[name] = op

		ep := &v1alpha1.KrakenDEndpoint{
			ObjectMeta: metav1.ObjectMeta{
				Name:      name,
				Namespace: ac.Namespace,
				Labels: map[string]string{
					LabelAutoGenerated: "true",
					LabelAutoConfig:    ac.Name,
				},
			},
			Spec: v1alpha1.KrakenDEndpointSpec{
				GatewayRef:       input.GatewayRef,
				Endpoints:        []v1alpha1.EndpointEntry{entry},
				ComponentSchemas: input.ComponentSchemas,
			},
		}
		output.Endpoints = append(output.Endpoints, ep)
	}

	return output, nil
}

// duplicateOf returns why an entry duplicates one generated before it (the
// same path and method, operationId, or endpoint name), with the identifier
// that collided, or "" when it does not. Each seen map records the operation
// ("METHOD /path") that claimed it.
func duplicateOf(
	key, opID, name string,
	seenKeys, seenOperationIDs, seenNames map[string]string,
) (ident, why string) {
	if by, ok := seenKeys[key]; ok {
		return key, fmt.Sprintf("same path and method as %s", by)
	}
	if by, ok := seenOperationIDs[opID]; ok && opID != "" {
		return opID, fmt.Sprintf("operationId %q is already used by %s", opID, by)
	}
	if by, ok := seenNames[name]; ok {
		return name, fmt.Sprintf("endpoint name %q is already used by %s", name, by)
	}
	return "", ""
}

// maxNameLength is the Kubernetes DNS-1123 subdomain name limit.
const maxNameLength = 253

func endpointName(autoconfigName, operationID, method, path string) string {
	if operationID != "" {
		return OperationEndpointName(autoconfigName, operationID)
	}
	return limitName(fmt.Sprintf("%s-%s-%s", autoconfigName, strings.ToLower(method), sanitizePath(path)))
}

// OperationEndpointName is the name of the KrakenDEndpoint generated for the
// operation operationID of the AutoConfig autoconfigName: the AutoConfig name
// and SanitizeName(operationID), cut to the Kubernetes name limit. Two
// operations with one name share one generated endpoint.
func OperationEndpointName(autoconfigName, operationID string) string {
	return limitName(fmt.Sprintf("%s-%s", autoconfigName, SanitizeName(operationID)))
}

func limitName(name string) string {
	if len(name) > maxNameLength {
		name = name[:maxNameLength]
	}
	return strings.TrimRight(name, "-")
}

// SanitizeName lowercases s and replaces every character outside [a-z0-9-]
// with "-", trimming leading and trailing dashes. It names generated endpoints
// and keys CUE overrides.
func SanitizeName(s string) string {
	s = strings.ToLower(s)
	s = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		return '-'
	}, s)
	return strings.Trim(s, "-")
}

func sanitizePath(path string) string {
	path = strings.TrimPrefix(path, "/")
	path = strings.ToLower(path)
	path = strings.ReplaceAll(path, "/", "-")
	path = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			return r
		}
		return -1
	}, path)
	return strings.Trim(path, "-")
}
