#!/usr/bin/env bash
# Regenerates THIRD-PARTY-NOTICES: the licenses and notices of everything the
# container image redistributes — the Go dependencies compiled into the
# manager binary, plus the KrakenD CE binary and musl libc copied in by the
# Dockerfile. Run via `make third-party-notices` after dependency changes.
set -euo pipefail

cd "$(dirname "$0")/.."

GO_LICENSES=${GO_LICENSES:-go-licenses}
OUT=THIRD-PARTY-NOTICES
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

"$GO_LICENSES" save ./cmd/... \
	--save_path="$TMP/licenses" \
	--ignore github.com/mycarrier-devops/krakend-operator

{
	echo "THIRD-PARTY NOTICES"
	echo
	echo "This file lists the third-party software redistributed with the KrakenD"
	echo "Operator container image, together with the corresponding license texts"
	echo "and notices. Generated by hack/gen-third-party-notices.sh."
	echo

	find "$TMP/licenses" -type f | sort | while read -r f; do
		rel=${f#"$TMP/licenses/"}
		echo "================================================================================"
		echo "${rel%/*} (${rel##*/})"
		echo "================================================================================"
		echo
		cat "$f"
		echo
	done

	cat hack/notices/krakend-ce.txt
	echo
	cat hack/notices/musl.txt
} >"$OUT"

echo "wrote $OUT ($(wc -c <"$OUT") bytes)"
