/*
Copyright 2026 The KrakenD Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"fmt"
	"maps"
	"slices"
	"strings"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	kerrors "k8s.io/apimachinery/pkg/util/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	v1alpha1 "github.com/mycarrier-devops/krakend-operator/api/v1alpha1"
	"github.com/mycarrier-devops/krakend-operator/internal/autoconfig"
	"github.com/mycarrier-devops/krakend-operator/internal/fieldindex"
)

// claimEndpoints returns the endpoints ac controls, found by the controller
// UID index, after adopting label-matched orphans the way a ReplicaSet adopts
// pods: an endpoint carrying both managed labels for ac, no controller
// reference and no deletion timestamp gets ac as its controller. An orphan
// that is in desired is left for writeEndpoint, which takes it over in the
// same write that updates it. An endpoint controlled by another object is
// never touched. Both lists are scoped to ac's namespace. Adoption failures
// are recorded in outcome.
func (r *KrakenDAutoConfigReconciler) claimEndpoints(
	ctx context.Context,
	ac *v1alpha1.KrakenDAutoConfig,
	desired []*v1alpha1.KrakenDEndpoint,
	outcome *endpointOutcome,
) ([]v1alpha1.KrakenDEndpoint, error) {
	var owned v1alpha1.KrakenDEndpointList
	if err := r.List(ctx, &owned, client.InNamespace(ac.Namespace),
		client.MatchingFields{fieldindex.EndpointController: string(ac.UID)},
	); err != nil {
		return nil, fmt.Errorf("listing controlled endpoints: %w", err)
	}
	var labelled v1alpha1.KrakenDEndpointList
	if err := r.List(ctx, &labelled, client.InNamespace(ac.Namespace),
		client.MatchingLabels{autoconfig.LabelAutoConfig: ac.Name, autoconfig.LabelAutoGenerated: "true"},
	); err != nil {
		return nil, fmt.Errorf("listing labelled endpoints: %w", err)
	}
	wanted := make(map[string]bool, len(desired))
	for _, ep := range desired {
		wanted[ep.Name] = true
	}
	// A cache lists in no particular order; adopt by name so the failures
	// of one pass read the same on every identical pass.
	slices.SortFunc(labelled.Items, func(a, b v1alpha1.KrakenDEndpoint) int {
		return strings.Compare(a.Name, b.Name)
	})
	controlled := owned.Items
	for i := range labelled.Items {
		orphan := &labelled.Items[i]
		if metav1.GetControllerOf(orphan) != nil || !orphan.DeletionTimestamp.IsZero() || wanted[orphan.Name] {
			continue
		}
		if err := controllerutil.SetControllerReference(ac, orphan, r.Scheme); err != nil {
			outcome.record(fmt.Errorf("adopting endpoint %s: %w", orphan.Name, err))
			continue
		}
		if err := r.Update(ctx, orphan); err != nil {
			outcome.record(fmt.Errorf("adopting endpoint %s: %w", orphan.Name, err))
			continue
		}
		controlled = append(controlled, *orphan)
	}
	return controlled, nil
}

// planEndpoints splits the work: writes are the desired endpoints that are
// missing from controlled or differ from their controlled copy, in desired
// order; stale are the controlled endpoints no longer desired, by name.
func planEndpoints(
	controlled []v1alpha1.KrakenDEndpoint,
	desired []*v1alpha1.KrakenDEndpoint,
) (writes []*v1alpha1.KrakenDEndpoint, stale []v1alpha1.KrakenDEndpoint) {
	byName := make(map[string]*v1alpha1.KrakenDEndpoint, len(controlled))
	for i := range controlled {
		byName[controlled[i].Name] = &controlled[i]
	}
	wanted := make(map[string]bool, len(desired))
	for _, ep := range desired {
		wanted[ep.Name] = true
		cur, ok := byName[ep.Name]
		if !ok || !labelsContain(cur.Labels, ep.Labels) || !endpointSpecEqual(cur.Spec, ep.Spec) {
			writes = append(writes, ep)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(byName)) {
		if !wanted[name] {
			stale = append(stale, *byName[name])
		}
	}
	return writes, stale
}

// labelsContain reports whether every label in want is set to the same value
// in have.
func labelsContain(have, want map[string]string) bool {
	for k, v := range want {
		if cur, ok := have[k]; !ok || cur != v {
			return false
		}
	}
	return true
}

// deleteEndpoint deletes a stale endpoint ac controls (claimEndpoints only
// returns those), preconditioned on its UID so a same-named replacement is
// never deleted. It reports whether this call deleted it; NotFound is not an
// error.
func (r *KrakenDAutoConfigReconciler) deleteEndpoint(
	ctx context.Context,
	ep *v1alpha1.KrakenDEndpoint,
) (bool, error) {
	err := r.Delete(ctx, ep, client.Preconditions{UID: &ep.UID})
	switch {
	case err == nil:
		return true, nil
	case apierrors.IsNotFound(err):
		return false, nil
	default:
		return false, fmt.Errorf("deleting endpoint %s: %w", ep.Name, err)
	}
}

// writeEndpoint creates or updates ep's live copy: it merges ep's labels into
// the existing ones, sets its spec and makes ac its controller. An endpoint
// of that name controlled by another object fails with
// controllerutil.AlreadyOwnedError.
func (r *KrakenDAutoConfigReconciler) writeEndpoint(
	ctx context.Context,
	ac *v1alpha1.KrakenDAutoConfig,
	ep *v1alpha1.KrakenDEndpoint,
) (controllerutil.OperationResult, error) {
	live := &v1alpha1.KrakenDEndpoint{ObjectMeta: metav1.ObjectMeta{Name: ep.Name, Namespace: ep.Namespace}}
	op, err := controllerutil.CreateOrUpdate(ctx, r.Client, live, func() error {
		if live.Labels == nil {
			live.Labels = map[string]string{}
		}
		maps.Copy(live.Labels, ep.Labels)
		if !endpointSpecEqual(live.Spec, ep.Spec) {
			live.Spec = ep.Spec
		}
		return controllerutil.SetControllerReference(ac, live, r.Scheme)
	})
	if err != nil {
		return op, fmt.Errorf("upserting endpoint %s: %w", ep.Name, err)
	}
	return op, nil
}

// endpointOutcome is what one reconcileEndpoints call did and could not do.
type endpointOutcome struct {
	changes endpointChanges
	// transient holds adoption, write and delete errors worth retrying with
	// backoff.
	transient []error
	// raced holds Conflict and AlreadyExists write errors: this reconcile
	// acted on a stale cache and loses nothing by retrying soon.
	raced []error
}

// failed reports whether any claim or write failed.
func (o *endpointOutcome) failed() bool {
	return len(o.transient) > 0 || len(o.raced) > 0
}

// record classifies a failed claim or write: a Conflict or AlreadyExists
// lost a race; anything else is retried with backoff.
func (o *endpointOutcome) record(err error) {
	if apierrors.IsConflict(err) || apierrors.IsAlreadyExists(err) {
		o.raced = append(o.raced, err)
		return
	}
	o.transient = append(o.transient, err)
}

// endpointFailures is every failure of one endpoint pass. Error is the whole
// list, for the log and the returned error; Summary names the first few and
// counts the rest, for the status and the event.
type endpointFailures struct {
	errs []error
}

func (f endpointFailures) Error() string {
	return kerrors.NewAggregate(f.errs).Error()
}

// Unwrap exposes the failures to errors.Is and errors.As.
func (f endpointFailures) Unwrap() []error {
	return f.errs
}

// Summary names the first failures, as listed does.
func (f endpointFailures) Summary() string {
	messages := make([]string, len(f.errs))
	for i, err := range f.errs {
		messages[i] = err.Error()
	}
	return listed(messages)
}
