/*
Copyright 2026 The KrakenD Operator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"maps"
	"math"
	"slices"
	"strings"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	kerrors "k8s.io/apimachinery/pkg/util/errors"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"

	v1alpha1 "github.com/mycarrier-devops/krakend-operator/api/v1alpha1"
	"github.com/mycarrier-devops/krakend-operator/internal/autoconfig"
	"github.com/mycarrier-devops/krakend-operator/internal/configcheck"
	"github.com/mycarrier-devops/krakend-operator/internal/fieldindex"
	"github.com/mycarrier-devops/krakend-operator/internal/renderer"
)

// AutoConfigChecker is the gateway config check the AutoConfig controller runs
// over the endpoints it is about to write (configcheck.Checker).
type AutoConfigChecker interface {
	CheckGateway(
		ctx context.Context,
		gw *v1alpha1.KrakenDGateway,
		replace []v1alpha1.KrakenDEndpoint,
	) (configcheck.Verdict, error)
}

// claimEndpoints returns the endpoints ac controls, found by the controller
// UID index, after adopting label-matched orphans the way a ReplicaSet adopts
// pods: an endpoint carrying both managed labels for ac, no controller
// reference and no deletion timestamp gets ac as its controller. An orphan
// that is in desired is left for writeEndpoint, which takes it over in the
// same write that updates it. An endpoint controlled by another object is
// never touched. Both lists are scoped to ac's namespace. Adoption failures
// are recorded in outcome.
func (r *KrakenDAutoConfigReconciler) claimEndpoints(
	ctx context.Context,
	ac *v1alpha1.KrakenDAutoConfig,
	desired []*v1alpha1.KrakenDEndpoint,
	outcome *endpointOutcome,
) ([]v1alpha1.KrakenDEndpoint, error) {
	var owned v1alpha1.KrakenDEndpointList
	if err := r.List(ctx, &owned, client.InNamespace(ac.Namespace),
		client.MatchingFields{fieldindex.EndpointController: string(ac.UID)},
	); err != nil {
		return nil, fmt.Errorf("listing controlled endpoints: %w", err)
	}
	var labelled v1alpha1.KrakenDEndpointList
	if err := r.List(ctx, &labelled, client.InNamespace(ac.Namespace),
		client.MatchingLabels{autoconfig.LabelAutoConfig: ac.Name, autoconfig.LabelAutoGenerated: "true"},
	); err != nil {
		return nil, fmt.Errorf("listing labelled endpoints: %w", err)
	}
	wanted := make(map[string]bool, len(desired))
	for _, ep := range desired {
		wanted[ep.Name] = true
	}
	// A cache lists in no particular order; adopt by name so the failures
	// of one pass read the same on every identical pass.
	slices.SortFunc(labelled.Items, func(a, b v1alpha1.KrakenDEndpoint) int {
		return strings.Compare(a.Name, b.Name)
	})
	controlled := owned.Items
	for i := range labelled.Items {
		orphan := &labelled.Items[i]
		if metav1.GetControllerOf(orphan) != nil || !orphan.DeletionTimestamp.IsZero() || wanted[orphan.Name] {
			continue
		}
		if err := controllerutil.SetControllerReference(ac, orphan, r.Scheme); err != nil {
			outcome.record(orphan, fmt.Errorf("adopting endpoint %s: %w", orphan.Name, err))
			continue
		}
		if err := r.Update(ctx, orphan); apierrors.IsNotFound(err) {
			// Deleted since the list: nothing left to adopt.
			continue
		} else if err != nil {
			outcome.record(orphan, fmt.Errorf("adopting endpoint %s: %w", orphan.Name, err))
			continue
		}
		controlled = append(controlled, *orphan)
	}
	return controlled, nil
}

// planEndpoints splits the work: writes are the desired endpoints that are
// missing from controlled or differ from their controlled copy, in desired
// order; stale are the controlled endpoints no longer desired, by name.
func planEndpoints(
	controlled []v1alpha1.KrakenDEndpoint,
	desired []*v1alpha1.KrakenDEndpoint,
) (writes []*v1alpha1.KrakenDEndpoint, stale []v1alpha1.KrakenDEndpoint) {
	byName := make(map[string]*v1alpha1.KrakenDEndpoint, len(controlled))
	for i := range controlled {
		byName[controlled[i].Name] = &controlled[i]
	}
	wanted := make(map[string]bool, len(desired))
	for _, ep := range desired {
		wanted[ep.Name] = true
		cur, ok := byName[ep.Name]
		if !ok || !labelsContain(cur.Labels, ep.Labels) || !endpointSpecEqual(cur.Spec, ep.Spec) {
			writes = append(writes, ep)
		}
	}
	for _, name := range slices.Sorted(maps.Keys(byName)) {
		if !wanted[name] {
			stale = append(stale, *byName[name])
		}
	}
	return writes, stale
}

// labelsContain reports whether every label in want is set to the same value
// in have.
func labelsContain(have, want map[string]string) bool {
	for k, v := range want {
		if cur, ok := have[k]; !ok || cur != v {
			return false
		}
	}
	return true
}

// deleteEndpoint deletes a stale endpoint ac controls (claimEndpoints only
// returns those), preconditioned on its UID so a same-named replacement is
// never deleted. It reports whether this call deleted it; NotFound is not an
// error.
func (r *KrakenDAutoConfigReconciler) deleteEndpoint(
	ctx context.Context,
	ep *v1alpha1.KrakenDEndpoint,
) (bool, error) {
	err := r.Delete(ctx, ep, client.Preconditions{UID: &ep.UID})
	switch {
	case err == nil:
		return true, nil
	case apierrors.IsNotFound(err):
		return false, nil
	default:
		return false, fmt.Errorf("deleting endpoint %s: %w", ep.Name, err)
	}
}

// writeEndpoint creates or updates ep's live copy: it merges ep's labels into
// the existing ones, sets its spec and makes ac its controller. An endpoint
// of that name controlled by another object fails with
// controllerutil.AlreadyOwnedError.
func (r *KrakenDAutoConfigReconciler) writeEndpoint(
	ctx context.Context,
	ac *v1alpha1.KrakenDAutoConfig,
	ep *v1alpha1.KrakenDEndpoint,
) (controllerutil.OperationResult, error) {
	live := &v1alpha1.KrakenDEndpoint{ObjectMeta: metav1.ObjectMeta{Name: ep.Name, Namespace: ep.Namespace}}
	op, err := controllerutil.CreateOrUpdate(ctx, r.Client, live, func() error {
		if live.Labels == nil {
			live.Labels = map[string]string{}
		}
		maps.Copy(live.Labels, ep.Labels)
		if !endpointSpecEqual(live.Spec, ep.Spec) {
			live.Spec = ep.Spec
		}
		return controllerutil.SetControllerReference(ac, live, r.Scheme)
	})
	if err != nil {
		return op, fmt.Errorf("upserting endpoint %s: %w", ep.Name, err)
	}
	return op, nil
}

// rejection is why an endpoint was not written.
type rejection struct {
	endpoint        *v1alpha1.KrakenDEndpoint
	reason, message string
	// cause is the full error, for the log: message is cut for the status.
	cause error
}

// endpointOutcome is what one reconcileEndpoints call did and could not do.
type endpointOutcome struct {
	changes endpointChanges
	// transient holds adoption, write and delete errors worth retrying with
	// backoff.
	transient []error
	// raced holds Conflict and AlreadyExists write errors: this reconcile
	// acted on a stale cache and loses nothing by retrying soon.
	raced []error
	// rejected holds the endpoints left unwritten for a persistent reason,
	// keyed by name: the API server rejected them as invalid, or another
	// object controls their name. Their existing endpoints are held.
	rejected map[string]rejection
}

// failed reports whether any claim or write failed.
func (o *endpointOutcome) failed() bool {
	return len(o.transient) > 0 || len(o.raced) > 0 || len(o.rejected) > 0
}

// record classifies a failed claim or write of ep: a Conflict or
// AlreadyExists lost a race, an Invalid rejection or a name another object
// controls is persistent, and anything else is retried with backoff.
func (o *endpointOutcome) record(ep *v1alpha1.KrakenDEndpoint, err error) {
	var owned *controllerutil.AlreadyOwnedError
	// The status names the endpoint already: leave out the wrap that says
	// which write failed.
	message := err.Error()
	if inner := errors.Unwrap(err); inner != nil {
		message = inner.Error()
	}
	switch {
	case apierrors.IsConflict(err) || apierrors.IsAlreadyExists(err):
		o.raced = append(o.raced, err)
	case apierrors.IsInvalid(err) || errors.As(err, &owned):
		o.rejected[ep.Name] = rejection{
			endpoint: ep, reason: v1alpha1.ReasonEndpointRejected, message: message, cause: err,
		}
	default:
		o.transient = append(o.transient, err)
	}
}

// endpointFailuresError is every failure of one endpoint pass. Error is the whole
// list, for the log and the returned error; Summary names the first few and
// counts the rest, for the status and the event.
type endpointFailuresError struct {
	errs []error
}

func (f endpointFailuresError) Error() string {
	return kerrors.NewAggregate(f.errs).Error()
}

// Summary names the first failures, as listed does.
func (f endpointFailuresError) Summary() string {
	messages := make([]string, len(f.errs))
	for i, err := range f.errs {
		messages[i] = err.Error()
	}
	return listed(messages)
}

// unattributedSummaryLimit bounds the findings text of a hold, in bytes.
const unattributedSummaryLimit = 200

// maxPrecheckRounds bounds the gateway config checks one reconcile runs to
// attribute a failing check to operations.
const maxPrecheckRounds = 5

// validatorUnavailableError marks a reconcileEndpoints failure caused by the
// gateway config check being unavailable (a transient condition).
type validatorUnavailableError struct{ err error }

func (e *validatorUnavailableError) Error() string { return "gateway config check: " + e.err.Error() }
func (e *validatorUnavailableError) Unwrap() error { return e.err }

// endpointFailureReason is the Synced reason for a reconcileEndpoints error:
// ValidatorUnavailable when the gateway config check could not run,
// EndpointReconcileFailed otherwise.
func endpointFailureReason(err error) string {
	var unavailable *validatorUnavailableError
	if errors.As(err, &unavailable) {
		return v1alpha1.ReasonValidatorUnavailable
	}
	return v1alpha1.ReasonEndpointReconcileFailed
}

// precheck runs the gateway config check over the endpoints reconcileEndpoints
// would write and returns those that fail it, keyed by name. Each round
// checks the remaining candidates, attributes the check's findings to them by
// Finding.Endpoint, and drops the attributed ones, until the check passes, no
// finding names a candidate, or maxPrecheckRounds rounds ran. A round models
// the state its writes would produce: when this reconcile will also delete
// the stale endpoints (held is false and nothing was held in an earlier
// round), they are replaced by empty copies so the check sees them gone. A
// missing gateway renders nothing, so nothing is checked. On a CE gateway,
// candidates that use Enterprise-only namespaces are held first (as
// EndpointRejected, the reason a refused write would give) and never checked:
// entry and backend namespaces are held without a write, while other
// admission rules the config check cannot see cost one rejected write per
// sync, which is held as EndpointRejected too. An error means the check could
// not run.
func (r *KrakenDAutoConfigReconciler) precheck(
	ctx context.Context,
	ac *v1alpha1.KrakenDAutoConfig,
	writes []*v1alpha1.KrakenDEndpoint,
	stale []v1alpha1.KrakenDEndpoint,
	held bool,
) (map[string]rejection, error) {
	rejected := map[string]rejection{}
	if len(writes) == 0 {
		return rejected, nil
	}
	var gw v1alpha1.KrakenDGateway
	gwKey := types.NamespacedName{
		Name:      ac.Spec.GatewayRef.Name,
		Namespace: ac.Spec.GatewayRef.ResolvedNamespace(ac.Namespace),
	}
	if err := r.Get(ctx, gwKey, &gw); err != nil {
		if apierrors.IsNotFound(err) {
			return rejected, nil
		}
		return nil, fmt.Errorf("getting gateway %s: %w", gwKey, err)
	}

	if gw.Spec.Edition == v1alpha1.EditionCE {
		for _, ep := range writes {
			if uses := ceIgnoredNamespaces(ep); len(uses) > 0 {
				message := fmt.Sprintf("not written: gateway %s runs CE, which ignores these Enterprise-only "+
					"namespaces: %s", gwKey, strings.Join(uses, ", "))
				rejected[ep.Name] = rejection{
					endpoint: ep, reason: v1alpha1.ReasonEndpointRejected, message: message, cause: errors.New(message),
				}
			}
		}
		writes = slices.DeleteFunc(slices.Clone(writes), func(ep *v1alpha1.KrakenDEndpoint) bool {
			_, ok := rejected[ep.Name]
			return ok
		})
	}

	candidates := writes
	for round := 0; len(candidates) > 0; round++ {
		if round == maxPrecheckRounds {
			message := fmt.Sprintf("not written: the gateway config check still failed after %d rounds",
				maxPrecheckRounds)
			hold(rejected, candidates, message, errors.New(message))
			return rejected, nil
		}
		verdict, err := r.Checker.CheckGateway(ctx, &gw, checkSet(candidates, stale, !held && len(rejected) == 0))
		if err != nil {
			return nil, &validatorUnavailableError{err: err}
		}
		if verdict.OK {
			return rejected, nil
		}
		attributed := attributeFindings(verdict.Findings, candidates)
		if len(attributed) == 0 {
			return r.unattributedFailure(ctx, &gw, candidates, verdict, rejected)
		}
		maps.Copy(rejected, attributed)
		candidates = slices.DeleteFunc(slices.Clone(candidates), func(ep *v1alpha1.KrakenDEndpoint) bool {
			_, ok := attributed[ep.Name]
			return ok
		})
	}
	return rejected, nil
}

// unattributedFailure handles a failed check whose findings name no
// candidate: gateway-root findings, or findings on endpoints outside this
// sync. When the gateway fails the check without the candidates too, the
// failure is not theirs and they are written. Otherwise the change as a whole
// breaks the gateway, and every candidate is held with the check's bounded
// summary.
func (r *KrakenDAutoConfigReconciler) unattributedFailure(
	ctx context.Context,
	gw *v1alpha1.KrakenDGateway,
	candidates []*v1alpha1.KrakenDEndpoint,
	verdict configcheck.Verdict,
	rejected map[string]rejection,
) (map[string]rejection, error) {
	baseline, err := r.Checker.CheckGateway(ctx, gw, nil)
	if err != nil {
		return nil, &validatorUnavailableError{err: err}
	}
	if !baseline.OK {
		return rejected, nil
	}
	const prefix = "the change fails the gateway config check: "
	hold(rejected, candidates, prefix+verdict.Summary(unattributedSummaryLimit),
		errors.New(prefix+verdict.Summary(math.MaxInt)))
	return rejected, nil
}

// hold records each endpoint in eps as failing the config check: message is
// for the status, cause the full text for the log.
func hold(rejected map[string]rejection, eps []*v1alpha1.KrakenDEndpoint, message string, cause error) {
	for _, ep := range eps {
		rejected[ep.Name] = rejection{
			endpoint: ep, reason: v1alpha1.ReasonConfigValidationFailed, message: message, cause: cause,
		}
	}
}

// ceIgnoredNamespaces lists each Enterprise-only extra_config namespace ep's
// entries and backends use, as "<field> <namespace>", with the keys CE drops
// when it honors the rest of the block. KrakenD CE accepts them in krakend
// check and ignores them, so the gateway config check cannot see them, and
// the endpoint webhook refuses them on a CE gateway.
func ceIgnoredNamespaces(ep *v1alpha1.KrakenDEndpoint) []string {
	var uses []string
	for i, e := range ep.Spec.Endpoints {
		entry := fmt.Sprintf("spec.endpoints[%d]", i)
		for _, d := range renderer.EEOnlyNamespacesIn(e.ExtraConfig, renderer.LevelEndpoint) {
			uses = append(uses, entry+".extraConfig "+d.String())
		}
		for j, be := range e.Backends {
			for _, d := range renderer.EEOnlyNamespacesIn(be.ExtraConfig, renderer.LevelBackend) {
				uses = append(uses, fmt.Sprintf("%s.backends[%d].extraConfig %s", entry, j, d.String()))
			}
		}
	}
	return uses
}

// checkSet is the replace set for one precheck round: the candidates, plus,
// when withoutStale, an empty copy of each stale endpoint, which renders no
// route and no schema.
func checkSet(
	candidates []*v1alpha1.KrakenDEndpoint,
	stale []v1alpha1.KrakenDEndpoint,
	withoutStale bool,
) []v1alpha1.KrakenDEndpoint {
	set := make([]v1alpha1.KrakenDEndpoint, 0, len(candidates)+len(stale))
	for _, ep := range candidates {
		set = append(set, *ep.DeepCopy())
	}
	if !withoutStale {
		return set
	}
	for i := range stale {
		gone := stale[i].DeepCopy()
		gone.Spec.Endpoints = nil
		gone.Spec.ComponentSchemas = nil
		set = append(set, *gone)
	}
	return set
}

// attributeFindings maps each candidate a finding's Endpoint names to its
// first finding. Finding.Index is the entry's position in that endpoint's
// spec.endpoints, or -1 when unknown; a generated endpoint has one entry, so
// either value means its single operation. A gateway-root finding (empty
// Endpoint) names no candidate.
func attributeFindings(
	findings []configcheck.Finding,
	candidates []*v1alpha1.KrakenDEndpoint,
) map[string]rejection {
	byKey := make(map[types.NamespacedName]*v1alpha1.KrakenDEndpoint, len(candidates))
	for _, ep := range candidates {
		byKey[types.NamespacedName{Namespace: ep.Namespace, Name: ep.Name}] = ep
	}
	attributed := map[string]rejection{}
	for _, f := range findings {
		ep, ok := byKey[f.Endpoint]
		if !ok {
			continue
		}
		if _, seen := attributed[ep.Name]; !seen {
			attributed[ep.Name] = rejection{
				endpoint: ep, reason: v1alpha1.ReasonConfigValidationFailed,
				message: f.Message, cause: errors.New(f.String()),
			}
		}
	}
	return attributed
}

// routeCollisions returns, keyed by name, the desired endpoints that lose
// their route to another desired endpoint. Endpoints are grouped by method and
// route shape (renderer.ConflictKey), the way the gateway's router tells
// routes apart: paths that differ only in parameter names or repeated slashes
// share a route, and only one of them is served. Stale endpoints take no part:
// while an operation is renamed its new endpoint and the old one share a route
// until the old one is deleted. The survivor of a group is the one the
// renderer serves.
func routeCollisions(
	desired []*v1alpha1.KrakenDEndpoint,
	controlled []v1alpha1.KrakenDEndpoint,
) map[string]rejection {
	groups := map[string][]*v1alpha1.KrakenDEndpoint{}
	for _, ep := range desired {
		if len(ep.Spec.Endpoints) == 0 {
			continue
		}
		e := ep.Spec.Endpoints[0]
		key := e.Method + " " + renderer.ConflictKey(e.Endpoint)
		groups[key] = append(groups[key], ep)
	}
	created := make(map[string]int64, len(controlled))
	for i := range controlled {
		created[controlled[i].Name] = controlled[i].CreationTimestamp.Unix()
	}
	// A new endpoint sorts after the existing ones.
	createdAt := func(name string) int64 {
		if t, ok := created[name]; ok {
			return t
		}
		return math.MaxInt64
	}
	collisions := map[string]rejection{}
	for _, group := range groups {
		slices.SortFunc(group, func(a, b *v1alpha1.KrakenDEndpoint) int {
			return cmp.Or(cmp.Compare(createdAt(a.Name), createdAt(b.Name)), strings.Compare(a.Name, b.Name))
		})
		survivor := group[0]
		for _, ep := range group[1:] {
			e := ep.Spec.Endpoints[0]
			message := renderer.RouteClashDetail(e.Method, e.Endpoint, survivor.Spec.Endpoints[0].Endpoint, survivor.Name)
			collisions[ep.Name] = rejection{
				endpoint: ep, reason: v1alpha1.ReasonConfigValidationFailed, message: message, cause: errors.New(message),
			}
		}
	}
	return collisions
}
